import { createSlice } from "@reduxjs/toolkit";

const offerSlice = createSlice({
  name: "offers",
  initialState: {
    list: [
      {
        id: 1,
        title: "React Bootcamp",
        subtitle: "Step-by-step React projects.",
        img: "https://i.ibb.co/F7v2wR9/react-bootcamp.jpg",
        badge: "Best Seller",
        price: "$59",
        oldPrice: "$119",
      },
      {
        id: 2,
        title: "Fullstack MERN",
        subtitle: "Become a complete developer.",
        img: "https://i.ibb.co/T4s4J1C/fullstack.jpg",
        badge: "New",
        price: "$79",
        oldPrice: "$159",
      },
      {
        id: 3,
        title: "UI/UX Design",
        subtitle: "Learn modern web design.",
        img: "https://i.ibb.co/ygVgZyP/web-design.jpg",
        badge: "Limited Time",
        price: "$49",
        oldPrice: "$99",
      },
      {
        id: 4,
        title: "JavaScript Mastery",
        subtitle: "Deep dive into JS concepts.",
        img: "https://i.ibb.co/5j5FfYy/javascript.jpg",
        badge: "Popular",
        price: "$39",
        oldPrice: "$79",
      },
      {
        id: 5,
        title: "Node.js Essentials",
        subtitle: "Backend development made easy.",
        img: "https://i.ibb.co/9t2s6Rg/nodejs.jpg",
        badge: "Hot",
        price: "$45",
        oldPrice: "$89",
      },
      {
        id: 6,
        title: "Python for Web",
        subtitle: "Learn Python fullstack web apps.",
        img: "https://i.ibb.co/4Wf6h5t/python.jpg",
        badge: "New",
        price: "$55",
        oldPrice: "$110",
      },
      {
        id: 7,
        title: "Data Science Pro",
        subtitle: "Master data analysis & ML.",
        img: "https://i.ibb.co/8dz4T8v/data-science.jpg",
        badge: "Trending",
        price: "$69",
        oldPrice: "$139",
      },
      {
        id: 8,
        title: "Angular Crash Course",
        subtitle: "Learn Angular from scratch.",
        img: "https://i.ibb.co/1RXGdHp/angular.jpg",
        badge: "Hot",
        price: "$49",
        oldPrice: "$99",
      },
      {
        id: 9,
        title: "Vue.js Essentials",
        subtitle: "Build modern web apps.",
        img: "https://i.ibb.co/q7RbNQd/vue.jpg",
        badge: "New",
        price: "$45",
        oldPrice: "$89",
      },
      {
        id: 10,
        title: "Django Fullstack",
        subtitle: "Python backend & frontend.",
        img: "https://i.ibb.co/Y2m6q9k/django.jpg",
        badge: "Popular",
        price: "$59",
        oldPrice: "$119",
      },
      {
        id: 11,
        title: "Flutter Mobile Dev",
        subtitle: "Build cross-platform apps.",
        img: "https://i.ibb.co/yh6Lw9K/flutter.jpg",
        badge: "Limited",
        price: "$69",
        oldPrice: "$139",
      },
      {
        id: 12,
        title: "AWS Cloud Expert",
        subtitle: "Deploy apps on AWS cloud.",
        img: "https://i.ibb.co/fp5pF36/aws.jpg",
        badge: "Hot",
        price: "$79",
        oldPrice: "$159",
      },
    ],
  },
  reducers: {},
});

export default offerSlice.reducer;
