import { createSlice } from "@reduxjs/toolkit";

const offerSlice = createSlice({
  name: "offers",
  initialState: {
    list: [
      {
        id: 1,
        title: "React Bootcamp",
        subtitle: "Step-by-step React projects.",
        img: "https://i.ibb.co/q3nWgqhX/images-q-tbn-ANd9-Gc-Teoqm-EC3hm-Au-YOLEFCitb-By-Zz66s-Qxr4-Gaiw-s.jpg",
        badge: "Best Seller",
        price: "$59",
        oldPrice: "$119",
      },
      {
        id: 2,
        title: "Fullstack MERN",
        subtitle: "Become a complete developer.",
        img: "https://i.ibb.co/FbJT8pcJ/images-q-tbn-ANd9-Gc-QMv-X8-HSXXK6ls-W7-ZYi-R9-PAAIk7t-AWC63l-GEC-A3-8-Y8-WVSv-Zhr-YCd-Wz-O1-FVna-VT.png",
        badge: "New",
        price: "$79",
        oldPrice: "$159",
      },
      {
        id: 3,
        title: "UI/UX Design",
        subtitle: "Learn modern web design.",
        img: "https://i.ibb.co/HDk5J8mn/images-q-tbn-ANd9-Gc-R-Ptp-PRIIo7-Lk-Utfueh-S2-Yb-IJ2-Nhx0x-3e-Sm-Pb-GWhi-N0r-Ve-SNy-HEb-fv-Rytz7k2m.jpg",
        badge: "Limited Time",
        price: "$49",
        oldPrice: "$99",
      },
      {
        id: 4,
        title: "JavaScript Mastery",
        subtitle: "Deep dive into JS concepts.",
        img: "https://i.ibb.co/8LHbSv09/images-q-tbn-ANd9-Gc-Tn4-FYr-JN6-CLh-06v-Kvx-Nz-Fie-VUOy4xg-Ll-HIx3i9m-Ht-Xjo9-YMtm52-NAgj73t1ucjj59.jpg",
        badge: "Popular",
        price: "$39",
        oldPrice: "$79",
      },
      {
        id: 5,
        title: "Node.js Essentials",
        subtitle: "Backend development made easy.",
        img: "https://i.ibb.co/LDZ0WF05/nodejs-cover-photo-smaller-size.png",
        badge: "Hot",
        price: "$45",
        oldPrice: "$89",
      },
      {
        id: 6,
        title: "Python for Web",
        subtitle: "Learn Python fullstack web apps.",
        img: "https://i.ibb.co/PvXnGgdh/pythonlogo.jpg",
        badge: "New",
        price: "$55",
        oldPrice: "$110",
      },
      {
        id: 7,
        title: "Data Science Pro",
        subtitle: "Master data analysis & ML.",
        img: "https://i.ibb.co/9m9hRRPG/What-is-data-science-2.jpg",
        badge: "Trending",
        price: "$69",
        oldPrice: "$139",
      },
      {
        id: 8,
        title: "Angular Crash Course",
        subtitle: "Learn Angular from scratch.",
        img: "https://i.ibb.co/8WRFcr9/1645127051-angular-snipcart.png",
        badge: "Hot",
        price: "$49",
        oldPrice: "$99",
      },
      {
        id: 9,
        title: "Vue.js Essentials",
        subtitle: "Build modern web apps.",
        img: "https://i.ibb.co/chzQ93n7/1381896-353e.jpg",
        badge: "New",
        price: "$45",
        oldPrice: "$89",
      },
      {
        id: 10,
        title: "Django Fullstack",
        subtitle: "Python backend & frontend.",
        img: "https://i.ibb.co/LDSLD4kQ/1694101907119-e-2147483647-v-beta-t-nwwk9owd0b-V2cu6-CJY4p-YN73ly4q-T-Wwy-Nswhj-Crwp-U.jpg",
        badge: "Popular",
        price: "$59",
        oldPrice: "$119",
      },
      {
        id: 11,
        title: "Flutter Mobile Dev",
        subtitle: "Build cross-platform apps.",
        img: "https://i.ibb.co/5xjPT3Wq/app-development-banner-33099-1720.jpg",
        badge: "Limited",
        price: "$69",
        oldPrice: "$139",
      },
      {
        id: 12,
        title: "AWS Cloud Expert",
        subtitle: "Deploy apps on AWS cloud.",
        img: "https://i.ibb.co/TqHDdmsq/5190186-ae36-2.jpg",
        badge: "Hot",
        price: "$79",
        oldPrice: "$159",
      },
    ],
  },
  reducers: {},
});

export default offerSlice.reducer;
